#!/usr/bin/env python3
"""Regenerate supabase/security/definer_inventory.md from a migrated database
(R6 WP-02). Usage: PGHOST=… PGDATABASE=… python3 scripts/db/definer-inventory.py
Lists every SECURITY DEFINER function in public with its grantees, what calls
it (policies, triggers, the app, Edge Functions) and its classification."""
import os, re, subprocess, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
SQL = r"""
select replace(regexp_replace(p.oid::regprocedure::text, '^public\.', ''), ', ', ',') as sig,
       p.proname,
       p.prorettype = 'trigger'::regtype as is_trigger,
       array_to_string(array(select r from unnest(array['anon','authenticated','service_role','timhirt_view_owner']) r
                             where exists (select 1 from pg_roles x where x.rolname = r)
                               and has_function_privilege(r, p.oid, 'execute')), ' ') as grantees,
       (select count(*) from pg_policy pol
         where coalesce(pg_get_expr(pol.polqual, pol.polrelid), '') || ' ' || coalesce(pg_get_expr(pol.polwithcheck, pol.polrelid), '')
               ~ ('\m' || p.proname || '\(')) as policies,
       (select count(*) from pg_trigger t where t.tgfoid = p.oid) as triggers,
       coalesce(array_to_string(p.proconfig, ','), '') as config
from pg_proc p join pg_namespace n on n.oid = p.pronamespace
where n.nspname = 'public' and p.prosecdef
  and not exists (select 1 from pg_depend d where d.classid = 'pg_proc'::regclass and d.objid = p.oid and d.deptype = 'e')
order by 1
"""
out = subprocess.run(["psql", "-qtA", "-F", "\t", "--no-psqlrc", "-c", SQL], capture_output=True, text=True, check=True).stdout

def callers(name, base):
    hits = []
    for p in (ROOT / base).rglob("*.ts*"):
        if ".test." in p.name:
            continue
        if re.search(r"rpc(<[^>]*>)?\(\s*[\"']" + re.escape(name) + r"[\"']", p.read_text(encoding="utf-8")):
            hits.append(p.relative_to(ROOT / base).parts[0] if base == "supabase/functions" else p.name)
    return sorted(set(hits))

rows = []
for line in out.strip().splitlines():
    sig, name, is_trigger, grantees, policies, triggers, config = line.split("\t")
    app, edge = callers(name, "src"), callers(name, "supabase/functions")
    g = set(grantees.split())
    if is_trigger == "t":
        cls = "Trigger-only"
    elif "anon" in g:
        cls = "Public (anon)"
    elif g & {"authenticated", "timhirt_view_owner"}:
        cls = "Private (authenticated)"
    else:
        cls = "Internal (service_role)"
    rows.append((sig, cls, grantees or "—", policies, triggers, ", ".join(app) or "—", ", ".join(edge) or "—", config))

md = ["# SECURITY DEFINER inventory (generated)", "",
      "Generated by `scripts/db/definer-inventory.py` from a database with every migration applied (R6 WP-02).",
      "Grantees exclude the owner (postgres). `Private` functions are reachable by signed-in users through PostgREST;",
      "`Internal` ones only by Edge Functions (service_role) and cron; trigger functions need no EXECUTE grant.",
      "The reviewed grant list is `definer_allowlist.sql`; `catalog_definer_security.sql` keeps the two in step.", "",
      f"{len(rows)} functions.", "",
      "| Function | Class | EXECUTE | Policies | Triggers | App callers | Edge Function callers | search_path |",
      "|---|---|---|---|---|---|---|---|"]
for r in rows:
    md.append("| `%s` | %s | %s | %s | %s | %s | %s | `%s` |" % r)
(ROOT / "supabase/security/definer_inventory.md").write_text("\n".join(md) + "\n", encoding="utf-8")
print(f"wrote {len(rows)} rows")
