// §6.4 strict allow-list validation — mirrored by DB constraints (§7.2)
import { z } from "zod";

// Error messages are short stable codes, not English sentences — this schema
// is built once at module load and can't react to a later language switch,
// so callers translate the code at display time (students.errors.<code>).
const NAME_RE = /^[\p{L}\p{M}'\- ]+$/u;

// English + Amharic spellings of each name part, matching the public /apply
// stepper's step1Schema (§ the tenant-side and public-side forms must
// collect identical fields — see migration 20260718000001).
export const studentSchema = z.object({
  first_name: z.string().trim().min(1, "required").max(80).regex(NAME_RE, "letters_only"),
  first_name_am: z.string().trim().min(1, "required").max(80).regex(NAME_RE, "letters_only"),
  middle_name: z.string().trim().min(1, "required").max(80).regex(NAME_RE, "letters_only"),
  middle_name_am: z.string().trim().min(1, "required").max(80).regex(NAME_RE, "letters_only"),
  last_name: z.string().trim().min(1, "required").max(80).regex(NAME_RE, "letters_only"),
  last_name_am: z.string().trim().min(1, "required").max(80).regex(NAME_RE, "letters_only"),
  // No admission_no here — the Student Number is generated by the DB on
  // insert (students_set_admission_no trigger, migration 20260719000005).
  date_of_birth: z.date({ errorMap: () => ({ message: "required" }) }).max(new Date(), "must_be_past"),
  gender: z.enum(["male", "female", "other"], { errorMap: () => ({ message: "required" }) }),
  // Optional, and shape-only: the set of groups lives in lib/ethnic-groups.ts
  // rather than in a constraint, so a school can be offered a new one without
  // a migration. "" means not recorded and is mapped to null before writing.
  ethnicity: z.string().regex(/^[a-z][a-z0-9_]{1,39}$/, "invalid").optional().or(z.literal("")),
  class_id: z.string().uuid("select_class"),
});
export type StudentInput = z.infer<typeof studentSchema>;
