-- ============================================================================
-- Telebirr H5 C2B payment gateway (replaces Chapa/Stripe), token cache, and
-- prep for a swappable SMS provider. See docs/school-saas-architecture-
-- blueprint.md §8.2 note: the blueprint's Stripe reference was aspirational
-- and never actually implemented; Chapa was the only real gateway. Both are
-- canceled by explicit decision — Telebirr's H5 C2B API (RSA-signed, real
-- request/response docs from Ethio Telecom) is the replacement.
--
-- registration_payment_method (cbe|awash_bank|telebirr), bank_verification_
-- domains, and bank_payment_verifications are DELIBERATELY untouched — that's
-- a separate manual-transfer-plus-receipt-verification mechanism (see the
-- updated comment atop _shared/bank-verify.ts), not this gateway.
-- ============================================================================

delete from public.platform_integrations where provider in ('chapa', 'stripe');

alter table public.platform_integrations
  drop constraint platform_integrations_provider_check,
  add constraint platform_integrations_provider_check
    check (provider in ('telebirr', 'sms_smsala', 'sms_afromessage', 'sms_geezsms')),
  add column config jsonb not null default '{}'::jsonb;
-- config holds NON-secret Telebirr identity/config:
--   environment              'testbed' | 'production' (testbed only, this build)
--   fabric_app_key            X-APP-Key header value (an identifier, not
--                             sufficient alone to authenticate -- appSecret,
--                             which stays in Vault, does that)
--   appid                     Mobile Payment application id (merchant portal)
--   merch_code                merchant short code
--   telebirr_public_key_pem   Telebirr's own public key, for verifying THEIR
--                             signed responses -- blank until Ethio Telecom
--                             supplies it (open item, not yet available)
--   our_public_key_pem        system-generated by telebirr-generate-keypair,
--                             safe to display -- it is not secret
--   key_generated_at          timestamptz string, system-written alongside it

insert into public.platform_integrations (provider, display_name) values
  ('telebirr', 'Telebirr (H5 C2B Web Payment)'),
  ('sms_smsala', 'SMSala'),
  ('sms_afromessage', 'AfroMessage'),
  ('sms_geezsms', 'GeezSMS')
on conflict (provider) do update set display_name = excluded.display_name;

-- Telebirr's own transaction id -- Chapa never had a slot for this, needed
-- for any future refund call (refundOrder's refund_request_no).
alter table public.payments add column provider_trans_id text;

-- Fabric token cache. Singleton row (id always true) so callers upsert
-- rather than accumulate rows. service_role only -- no client-reachable
-- select policy, same "not client-forgeable" shape as webhook_events.
create table public.telebirr_token_cache (
  id           boolean primary key default true check (id),
  token        text not null,
  effective_at timestamptz not null,
  expires_at   timestamptz not null,
  updated_at   timestamptz not null default now()
);
alter table public.telebirr_token_cache enable row level security;
alter table public.telebirr_token_cache force row level security;
-- No policies at all: unreachable via PostgREST for every role except
-- service_role, which bypasses RLS by design.

insert into public.system_config (tenant_id, key, value, value_type, description) values
  (null, 'active_sms_provider', 'null'::jsonb, 'string',
   'sms_smsala | sms_afromessage | sms_geezsms | null (SMS sending disabled). Adapters are best-effort/unverified -- see _shared/sms.ts.')
on conflict (tenant_id, key) do nothing;
